import React, { useState } from "react";
import { storiesOf } from "@storybook/react";
import { select } from '@storybook/addon-knobs';
import { ThemeProvider } from '../../index';
import { BaseStyles } from '../BaseStyles';
import { Icon } from './index';
import { Flex, FlexItem } from "../Flex";
import { StyledInput } from "../Input";

storiesOf("Icon", module)
  .add("Default", () => {
    const color = select('Color', [
      'primary',
      'secondary',
      'tertiary',
      'success',
      'danger',
      'warning',
      'dark',
      'medium',
      'light',
    ], 'primary');
    const [icons, setIcons] = useState<{ key: string, file: string }[]>([...allIcons].splice(0,100));

    const filterIcons = (term: string = '') => {
      if (!term.length) {
        const subset = [...allIcons].splice(0, 100);
        setIcons(subset);
        return;
      }

      const filteredIcons = allIcons.filter((icon) => {
        return icon.key.toLowerCase().indexOf(term.toLowerCase()) > -1;
      });

      if (filteredIcons) {
        setIcons(filteredIcons);
      } else {
        setIcons([]);
      }
    }

    return (
      <ThemeProvider>
        <BaseStyles />
        <StyledInput type="search" placeholder="Search..." onChange={(e) => filterIcons(e.target.value)} />
        <Flex wrap alignCenter>
          {icons.map((icon, index: number) => (
            <FlexItem key={index} basis="10%">
              <div style={{ border: '1px solid #eee', padding: '16px', textAlign: 'center' }}>
                <Icon icon={icon.key} color={color} />
                <p style={{ textAlign: 'center', fontSize: '10px' }}>{icon.key}</p>
              </div>
            </FlexItem>
          ))}
        </Flex>
      </ThemeProvider>
    )
  })

const allIcons = [
  { key: '500px', file: '500px.svg' },
  { key: 'IE', file: 'IE.svg' },
  { key: 'IcoMoon', file: 'IcoMoon.svg' },
  { key: 'accessibility', file: 'accessibility.svg' },
  { key: 'address-book', file: 'address-book.svg' },
  { key: 'aid-kit', file: 'aid-kit.svg' },
  { key: 'airplane', file: 'airplane.svg' },
  { key: 'alarm', file: 'alarm.svg' },
  { key: 'amazon', file: 'amazon.svg' },
  { key: 'android', file: 'android.svg' },
  { key: 'angry', file: 'angry.svg' },
  { key: 'angry2', file: 'angry2.svg' },
  { key: 'appleinc', file: 'appleinc.svg' },
  { key: 'arrow-down-left', file: 'arrow-down-left.svg' },
  { key: 'arrow-down-left2', file: 'arrow-down-left2.svg' },
  { key: 'arrow-down-right', file: 'arrow-down-right.svg' },
  { key: 'arrow-down-right2', file: 'arrow-down-right2.svg' },
  { key: 'arrow-down', file: 'arrow-down.svg' },
  { key: 'arrow-down2', file: 'arrow-down2.svg' },
  { key: 'arrow-left', file: 'arrow-left.svg' },
  { key: 'arrow-left2', file: 'arrow-left2.svg' },
  { key: 'arrow-right', file: 'arrow-right.svg' },
  { key: 'arrow-right2', file: 'arrow-right2.svg' },
  { key: 'arrow-up-left', file: 'arrow-up-left.svg' },
  { key: 'arrow-up-left2', file: 'arrow-up-left2.svg' },
  { key: 'arrow-up-right', file: 'arrow-up-right.svg' },
  { key: 'arrow-up-right2', file: 'arrow-up-right2.svg' },
  { key: 'arrow-up', file: 'arrow-up.svg' },
  { key: 'arrow-up2', file: 'arrow-up2.svg' },
  { key: 'attachment', file: 'attachment.svg' },
  { key: 'backward', file: 'backward.svg' },
  { key: 'backward2', file: 'backward2.svg' },
  { key: 'baffled', file: 'baffled.svg' },
  { key: 'baffled2', file: 'baffled2.svg' },
  { key: 'barcode', file: 'barcode.svg' },
  { key: 'basecamp', file: 'basecamp.svg' },
  { key: 'behance', file: 'behance.svg' },
  { key: 'behance2', file: 'behance2.svg' },
  { key: 'bell', file: 'bell.svg' },
  { key: 'bin', file: 'bin.svg' },
  { key: 'bin2', file: 'bin2.svg' },
  { key: 'binoculars', file: 'binoculars.svg' },
  { key: 'blocked', file: 'blocked.svg' },
  { key: 'blog', file: 'blog.svg' },
  { key: 'blogger', file: 'blogger.svg' },
  { key: 'blogger2', file: 'blogger2.svg' },
  { key: 'bold', file: 'bold.svg' },
  { key: 'book', file: 'book.svg' },
  { key: 'bookmark', file: 'bookmark.svg' },
  { key: 'bookmarks', file: 'bookmarks.svg' },
  { key: 'books', file: 'books.svg' },
  { key: 'box-add', file: 'box-add.svg' },
  { key: 'box-remove', file: 'box-remove.svg' },
  { key: 'briefcase', file: 'briefcase.svg' },
  { key: 'brightness-contrast', file: 'brightness-contrast.svg' },
  { key: 'bubble', file: 'bubble.svg' },
  { key: 'bubble2', file: 'bubble2.svg' },
  { key: 'bubbles', file: 'bubbles.svg' },
  { key: 'bubbles2', file: 'bubbles2.svg' },
  { key: 'bubbles3', file: 'bubbles3.svg' },
  { key: 'bubbles4', file: 'bubbles4.svg' },
  { key: 'bug', file: 'bug.svg' },
  { key: 'bullhorn', file: 'bullhorn.svg' },
  { key: 'calculator', file: 'calculator.svg' },
  { key: 'calendar', file: 'calendar.svg' },
  { key: 'camera', file: 'camera.svg' },
  { key: 'cancel-circle', file: 'cancel-circle.svg' },
  { key: 'cart', file: 'cart.svg' },
  { key: 'checkbox-checked', file: 'checkbox-checked.svg' },
  { key: 'checkbox-unchecked', file: 'checkbox-unchecked.svg' },
  { key: 'checkmark', file: 'checkmark.svg' },
  { key: 'checkmark2', file: 'checkmark2.svg' },
  { key: 'chrome', file: 'chrome.svg' },
  { key: 'circle-down', file: 'circle-down.svg' },
  { key: 'circle-left', file: 'circle-left.svg' },
  { key: 'circle-right', file: 'circle-right.svg' },
  { key: 'circle-up', file: 'circle-up.svg' },
  { key: 'clear-formatting', file: 'clear-formatting.svg' },
  { key: 'clipboard', file: 'clipboard.svg' },
  { key: 'clock', file: 'clock.svg' },
  { key: 'clock2', file: 'clock2.svg' },
  { key: 'cloud-check', file: 'cloud-check.svg' },
  { key: 'cloud-download', file: 'cloud-download.svg' },
  { key: 'cloud-upload', file: 'cloud-upload.svg' },
  { key: 'cloud', file: 'cloud.svg' },
  { key: 'clubs', file: 'clubs.svg' },
  { key: 'codepen', file: 'codepen.svg' },
  { key: 'cog', file: 'cog.svg' },
  { key: 'cogs', file: 'cogs.svg' },
  { key: 'coin-dollar', file: 'coin-dollar.svg' },
  { key: 'coin-euro', file: 'coin-euro.svg' },
  { key: 'coin-pound', file: 'coin-pound.svg' },
  { key: 'coin-yen', file: 'coin-yen.svg' },
  { key: 'command', file: 'command.svg' },
  { key: 'compass', file: 'compass.svg' },
  { key: 'compass2', file: 'compass2.svg' },
  { key: 'confused', file: 'confused.svg' },
  { key: 'confused2', file: 'confused2.svg' },
  { key: 'connection', file: 'connection.svg' },
  { key: 'contrast', file: 'contrast.svg' },
  { key: 'cool', file: 'cool.svg' },
  { key: 'cool2', file: 'cool2.svg' },
  { key: 'copy', file: 'copy.svg' },
  { key: 'credit-card', file: 'credit-card.svg' },
  { key: 'crop', file: 'crop.svg' },
  { key: 'cross', file: 'cross.svg' },
  { key: 'crying', file: 'crying.svg' },
  { key: 'crying2', file: 'crying2.svg' },
  { key: 'css3', file: 'css3.svg' },
  { key: 'ctrl', file: 'ctrl.svg' },
  { key: 'database', file: 'database.svg' },
  { key: 'delicious', file: 'delicious.svg' },
  { key: 'deviantart', file: 'deviantart.svg' },
  { key: 'diamonds', file: 'diamonds.svg' },
  { key: 'dice', file: 'dice.svg' },
  { key: 'display', file: 'display.svg' },
  { key: 'download', file: 'download.svg' },
  { key: 'download2', file: 'download2.svg' },
  { key: 'download3', file: 'download3.svg' },
  { key: 'drawer', file: 'drawer.svg' },
  { key: 'drawer2', file: 'drawer2.svg' },
  { key: 'dribbble', file: 'dribbble.svg' },
  { key: 'drive', file: 'drive.svg' },
  { key: 'dropbox', file: 'dropbox.svg' },
  { key: 'droplet', file: 'droplet.svg' },
  { key: 'earth', file: 'earth.svg' },
  { key: 'edge', file: 'edge.svg' },
  { key: 'eject', file: 'eject.svg' },
  { key: 'ello', file: 'ello.svg' },
  { key: 'embed', file: 'embed.svg' },
  { key: 'embed2', file: 'embed2.svg' },
  { key: 'enlarge', file: 'enlarge.svg' },
  { key: 'enlarge2', file: 'enlarge2.svg' },
  { key: 'enter', file: 'enter.svg' },
  { key: 'envelop', file: 'envelop.svg' },
  { key: 'equalizer', file: 'equalizer.svg' },
  { key: 'equalizer2', file: 'equalizer2.svg' },
  { key: 'evil', file: 'evil.svg' },
  { key: 'evil2', file: 'evil2.svg' },
  { key: 'exit', file: 'exit.svg' },
  { key: 'eye-blocked', file: 'eye-blocked.svg' },
  { key: 'eye-minus', file: 'eye-minus.svg' },
  { key: 'eye-plus', file: 'eye-plus.svg' },
  { key: 'eye', file: 'eye.svg' },
  { key: 'eyedropper', file: 'eyedropper.svg' },
  { key: 'facebook', file: 'facebook.svg' },
  { key: 'facebook2', file: 'facebook2.svg' },
  { key: 'feed', file: 'feed.svg' },
  { key: 'file-empty', file: 'file-empty.svg' },
  { key: 'file-excel', file: 'file-excel.svg' },
  { key: 'file-music', file: 'file-music.svg' },
  { key: 'file-openoffice', file: 'file-openoffice.svg' },
  { key: 'file-pdf', file: 'file-pdf.svg' },
  { key: 'file-picture', file: 'file-picture.svg' },
  { key: 'file-play', file: 'file-play.svg' },
  { key: 'file-text', file: 'file-text.svg' },
  { key: 'file-text2', file: 'file-text2.svg' },
  { key: 'file-video', file: 'file-video.svg' },
  { key: 'file-word', file: 'file-word.svg' },
  { key: 'file-zip', file: 'file-zip.svg' },
  { key: 'files-empty', file: 'files-empty.svg' },
  { key: 'film', file: 'film.svg' },
  { key: 'filter', file: 'filter.svg' },
  { key: 'finder', file: 'finder.svg' },
  { key: 'fire', file: 'fire.svg' },
  { key: 'firefox', file: 'firefox.svg' },
  { key: 'first', file: 'first.svg' },
  { key: 'flag', file: 'flag.svg' },
  { key: 'flattr', file: 'flattr.svg' },
  { key: 'flickr', file: 'flickr.svg' },
  { key: 'flickr2', file: 'flickr2.svg' },
  { key: 'flickr3', file: 'flickr3.svg' },
  { key: 'flickr4', file: 'flickr4.svg' },
  { key: 'floppy-disk', file: 'floppy-disk.svg' },
  { key: 'folder-download', file: 'folder-download.svg' },
  { key: 'folder-minus', file: 'folder-minus.svg' },
  { key: 'folder-open', file: 'folder-open.svg' },
  { key: 'folder-plus', file: 'folder-plus.svg' },
  { key: 'folder-upload', file: 'folder-upload.svg' },
  { key: 'folder', file: 'folder.svg' },
  { key: 'font-size', file: 'font-size.svg' },
  { key: 'font', file: 'font.svg' },
  { key: 'forward', file: 'forward.svg' },
  { key: 'forward2', file: 'forward2.svg' },
  { key: 'forward3', file: 'forward3.svg' },
  { key: 'foursquare', file: 'foursquare.svg' },
  { key: 'frustrated', file: 'frustrated.svg' },
  { key: 'frustrated2', file: 'frustrated2.svg' },
  { key: 'gift', file: 'gift.svg' },
  { key: 'git', file: 'git.svg' },
  { key: 'github', file: 'github.svg' },
  { key: 'glass', file: 'glass.svg' },
  { key: 'glass2', file: 'glass2.svg' },
  { key: 'google-drive', file: 'google-drive.svg' },
  { key: 'google-plus', file: 'google-plus.svg' },
  { key: 'google-plus2', file: 'google-plus2.svg' },
  { key: 'google-plus3', file: 'google-plus3.svg' },
  { key: 'google', file: 'google.svg' },
  { key: 'google2', file: 'google2.svg' },
  { key: 'google3', file: 'google3.svg' },
  { key: 'grin', file: 'grin.svg' },
  { key: 'grin2', file: 'grin2.svg' },
  { key: 'hackernews', file: 'hackernews.svg' },
  { key: 'hammer', file: 'hammer.svg' },
  { key: 'hammer2', file: 'hammer2.svg' },
  { key: 'hangouts', file: 'hangouts.svg' },
  { key: 'happy', file: 'happy.svg' },
  { key: 'happy2', file: 'happy2.svg' },
  { key: 'headphones', file: 'headphones.svg' },
  { key: 'heart-broken', file: 'heart-broken.svg' },
  { key: 'heart', file: 'heart.svg' },
  { key: 'hipster', file: 'hipster.svg' },
  { key: 'hipster2', file: 'hipster2.svg' },
  { key: 'history', file: 'history.svg' },
  { key: 'home', file: 'home.svg' },
  { key: 'home2', file: 'home2.svg' },
  { key: 'home3', file: 'home3.svg' },
  { key: 'hour-glass', file: 'hour-glass.svg' },
  { key: 'html-five', file: 'html-five.svg' },
  { key: 'html-five2', file: 'html-five2.svg' },
  { key: 'image', file: 'image.svg' },
  { key: 'images', file: 'images.svg' },
  { key: 'indent-decrease', file: 'indent-decrease.svg' },
  { key: 'indent-increase', file: 'indent-increase.svg' },
  { key: 'infinite', file: 'infinite.svg' },
  { key: 'info', file: 'info.svg' },
  { key: 'insert-template', file: 'insert-template.svg' },
  { key: 'instagram', file: 'instagram.svg' },
  { key: 'italic', file: 'italic.svg' },
  { key: 'joomla', file: 'joomla.svg' },
  { key: 'key', file: 'key.svg' },
  { key: 'key2', file: 'key2.svg' },
  { key: 'keyboard', file: 'keyboard.svg' },
  { key: 'lab', file: 'lab.svg' },
  { key: 'lanyrd', file: 'lanyrd.svg' },
  { key: 'laptop', file: 'laptop.svg' },
  { key: 'last', file: 'last.svg' },
  { key: 'lastfm', file: 'lastfm.svg' },
  { key: 'lastfm2', file: 'lastfm2.svg' },
  { key: 'leaf', file: 'leaf.svg' },
  { key: 'library', file: 'library.svg' },
  { key: 'libreoffice', file: 'libreoffice.svg' },
  { key: 'lifebuoy', file: 'lifebuoy.svg' },
  { key: 'ligature', file: 'ligature.svg' },
  { key: 'ligature2', file: 'ligature2.svg' },
  { key: 'link', file: 'link.svg' },
  { key: 'linkedin', file: 'linkedin.svg' },
  { key: 'linkedin2', file: 'linkedin2.svg' },
  { key: 'list-numbered', file: 'list-numbered.svg' },
  { key: 'list', file: 'list.svg' },
  { key: 'list2', file: 'list2.svg' },
  { key: 'location', file: 'location.svg' },
  { key: 'location2', file: 'location2.svg' },
  { key: 'lock', file: 'lock.svg' },
  { key: 'loop', file: 'loop.svg' },
  { key: 'loop2', file: 'loop2.svg' },
  { key: 'ltr', file: 'ltr.svg' },
  { key: 'magic-wand', file: 'magic-wand.svg' },
  { key: 'magnet', file: 'magnet.svg' },
  { key: 'mail', file: 'mail.svg' },
  { key: 'mail2', file: 'mail2.svg' },
  { key: 'mail3', file: 'mail3.svg' },
  { key: 'mail4', file: 'mail4.svg' },
  { key: 'make-group', file: 'make-group.svg' },
  { key: 'man-woman', file: 'man-woman.svg' },
  { key: 'man', file: 'man.svg' },
  { key: 'map', file: 'map.svg' },
  { key: 'map2', file: 'map2.svg' },
  { key: 'menu', file: 'menu.svg' },
  { key: 'menu2', file: 'menu2.svg' },
  { key: 'menu3', file: 'menu3.svg' },
  { key: 'menu4', file: 'menu4.svg' },
  { key: 'meter', file: 'meter.svg' },
  { key: 'meter2', file: 'meter2.svg' },
  { key: 'mic', file: 'mic.svg' },
  { key: 'minus', file: 'minus.svg' },
  { key: 'mobile', file: 'mobile.svg' },
  { key: 'mobile2', file: 'mobile2.svg' },
  { key: 'move-down', file: 'move-down.svg' },
  { key: 'move-up', file: 'move-up.svg' },
  { key: 'mug', file: 'mug.svg' },
  { key: 'music', file: 'music.svg' },
  { key: 'neutral', file: 'neutral.svg' },
  { key: 'neutral2', file: 'neutral2.svg' },
  { key: 'new-tab', file: 'new-tab.svg' },
  { key: 'newspaper', file: 'newspaper.svg' },
  { key: 'next', file: 'next.svg' },
  { key: 'next2', file: 'next2.svg' },
  { key: 'notification', file: 'notification.svg' },
  { key: 'npm', file: 'npm.svg' },
  { key: 'office', file: 'office.svg' },
  { key: 'omega', file: 'omega.svg' },
  { key: 'onedrive', file: 'onedrive.svg' },
  { key: 'opera', file: 'opera.svg' },
  { key: 'opt', file: 'opt.svg' },
  { key: 'pacman', file: 'pacman.svg' },
  { key: 'page-break', file: 'page-break.svg' },
  { key: 'pagebreak', file: 'pagebreak.svg' },
  { key: 'paint-format', file: 'paint-format.svg' },
  { key: 'paragraph-center', file: 'paragraph-center.svg' },
  { key: 'paragraph-justify', file: 'paragraph-justify.svg' },
  { key: 'paragraph-left', file: 'paragraph-left.svg' },
  { key: 'paragraph-right', file: 'paragraph-right.svg' },
  { key: 'paste', file: 'paste.svg' },
  { key: 'pause', file: 'pause.svg' },
  { key: 'pause2', file: 'pause2.svg' },
  { key: 'paypal', file: 'paypal.svg' },
  { key: 'pen', file: 'pen.svg' },
  { key: 'pencil', file: 'pencil.svg' },
  { key: 'pencil2', file: 'pencil2.svg' },
  { key: 'phone-hang-up', file: 'phone-hang-up.svg' },
  { key: 'phone', file: 'phone.svg' },
  { key: 'pie-chart', file: 'pie-chart.svg' },
  { key: 'pilcrow', file: 'pilcrow.svg' },
  { key: 'pinterest', file: 'pinterest.svg' },
  { key: 'pinterest2', file: 'pinterest2.svg' },
  { key: 'play', file: 'play.svg' },
  { key: 'play2', file: 'play2.svg' },
  { key: 'play3', file: 'play3.svg' },
  { key: 'plus', file: 'plus.svg' },
  { key: 'podcast', file: 'podcast.svg' },
  { key: 'point-down', file: 'point-down.svg' },
  { key: 'point-left', file: 'point-left.svg' },
  { key: 'point-right', file: 'point-right.svg' },
  { key: 'point-up', file: 'point-up.svg' },
  { key: 'power-cord', file: 'power-cord.svg' },
  { key: 'power', file: 'power.svg' },
  { key: 'previous', file: 'previous.svg' },
  { key: 'previous2', file: 'previous2.svg' },
  { key: 'price-tag', file: 'price-tag.svg' },
  { key: 'price-tags', file: 'price-tags.svg' },
  { key: 'printer', file: 'printer.svg' },
  { key: 'profile', file: 'profile.svg' },
  { key: 'pushpin', file: 'pushpin.svg' },
  { key: 'qrcode', file: 'qrcode.svg' },
  { key: 'question', file: 'question.svg' },
  { key: 'quill', file: 'quill.svg' },
  { key: 'quotes-left', file: 'quotes-left.svg' },
  { key: 'quotes-right', file: 'quotes-right.svg' },
  { key: 'radio-checked', file: 'radio-checked.svg' },
  { key: 'radio-checked2', file: 'radio-checked2.svg' },
  { key: 'radio-unchecked', file: 'radio-unchecked.svg' },
  { key: 'reddit', file: 'reddit.svg' },
  { key: 'redo', file: 'redo.svg' },
  { key: 'redo2', file: 'redo2.svg' },
  { key: 'renren', file: 'renren.svg' },
  { key: 'reply', file: 'reply.svg' },
  { key: 'road', file: 'road.svg' },
  { key: 'rocket', file: 'rocket.svg' },
  { key: 'rss', file: 'rss.svg' },
  { key: 'rss2', file: 'rss2.svg' },
  { key: 'rtl', file: 'rtl.svg' },
  { key: 'sad', file: 'sad.svg' },
  { key: 'sad2', file: 'sad2.svg' },
  { key: 'safari', file: 'safari.svg' },
  { key: 'scissors', file: 'scissors.svg' },
  { key: 'search', file: 'search.svg' },
  { key: 'section', file: 'section.svg' },
  { key: 'share', file: 'share.svg' },
  { key: 'share2', file: 'share2.svg' },
  { key: 'shield', file: 'shield.svg' },
  { key: 'shift', file: 'shift.svg' },
  { key: 'shocked', file: 'shocked.svg' },
  { key: 'shocked2', file: 'shocked2.svg' },
  { key: 'shrink', file: 'shrink.svg' },
  { key: 'shrink2', file: 'shrink2.svg' },
  { key: 'shuffle', file: 'shuffle.svg' },
  { key: 'sigma', file: 'sigma.svg' },
  { key: 'sina-weibo', file: 'sina-weibo.svg' },
  { key: 'skype', file: 'skype.svg' },
  { key: 'sleepy', file: 'sleepy.svg' },
  { key: 'sleepy2', file: 'sleepy2.svg' },
  { key: 'smile', file: 'smile.svg' },
  { key: 'smile2', file: 'smile2.svg' },
  { key: 'sort-alpha-asc', file: 'sort-alpha-asc.svg' },
  { key: 'sort-alpha-desc', file: 'sort-alpha-desc.svg' },
  { key: 'sort-amount-asc', file: 'sort-amount-asc.svg' },
  { key: 'sort-amount-desc', file: 'sort-amount-desc.svg' },
  { key: 'sort-numberic-desc', file: 'sort-numberic-desc.svg' },
  { key: 'sort-numeric-asc', file: 'sort-numeric-asc.svg' },
  { key: 'soundcloud', file: 'soundcloud.svg' },
  { key: 'soundcloud2', file: 'soundcloud2.svg' },
  { key: 'spades', file: 'spades.svg' },
  { key: 'spell-check', file: 'spell-check.svg' },
  { key: 'sphere', file: 'sphere.svg' },
  { key: 'spinner', file: 'spinner.svg' },
  { key: 'spinner10', file: 'spinner10.svg' },
  { key: 'spinner11', file: 'spinner11.svg' },
  { key: 'spinner2', file: 'spinner2.svg' },
  { key: 'spinner3', file: 'spinner3.svg' },
  { key: 'spinner4', file: 'spinner4.svg' },
  { key: 'spinner5', file: 'spinner5.svg' },
  { key: 'spinner6', file: 'spinner6.svg' },
  { key: 'spinner7', file: 'spinner7.svg' },
  { key: 'spinner8', file: 'spinner8.svg' },
  { key: 'spinner9', file: 'spinner9.svg' },
  { key: 'spoon-knife', file: 'spoon-knife.svg' },
  { key: 'spotify', file: 'spotify.svg' },
  { key: 'stack', file: 'stack.svg' },
  { key: 'stackoverflow', file: 'stackoverflow.svg' },
  { key: 'star-empty', file: 'star-empty.svg' },
  { key: 'star-full', file: 'star-full.svg' },
  { key: 'star-half', file: 'star-half.svg' },
  { key: 'stats-bars', file: 'stats-bars.svg' },
  { key: 'stats-bars2', file: 'stats-bars2.svg' },
  { key: 'stats-dots', file: 'stats-dots.svg' },
  { key: 'steam', file: 'steam.svg' },
  { key: 'steam2', file: 'steam2.svg' },
  { key: 'stop', file: 'stop.svg' },
  { key: 'stop2', file: 'stop2.svg' },
  { key: 'stopwatch', file: 'stopwatch.svg' },
  { key: 'strikethrough', file: 'strikethrough.svg' },
  { key: 'stumbleupon', file: 'stumbleupon.svg' },
  { key: 'stumbleupon2', file: 'stumbleupon2.svg' },
  { key: 'subscript', file: 'subscript.svg' },
  { key: 'subscript2', file: 'subscript2.svg' },
  { key: 'sun', file: 'sun.svg' },
  { key: 'superscript', file: 'superscript.svg' },
  { key: 'superscript2', file: 'superscript2.svg' },
  { key: 'svg', file: 'svg.svg' },
  { key: 'switch', file: 'switch.svg' },
  { key: 'tab', file: 'tab.svg' },
  { key: 'table', file: 'table.svg' },
  { key: 'table2', file: 'table2.svg' },
  { key: 'tablet', file: 'tablet.svg' },
  { key: 'target', file: 'target.svg' },
  { key: 'telegram', file: 'telegram.svg' },
  { key: 'terminal', file: 'terminal.svg' },
  { key: 'text-color', file: 'text-color.svg' },
  { key: 'text-height', file: 'text-height.svg' },
  { key: 'text-width', file: 'text-width.svg' },
  { key: 'ticket', file: 'ticket.svg' },
  { key: 'tongue', file: 'tongue.svg' },
  { key: 'tongue2', file: 'tongue2.svg' },
  { key: 'tree', file: 'tree.svg' },
  { key: 'trello', file: 'trello.svg' },
  { key: 'trophy', file: 'trophy.svg' },
  { key: 'truck', file: 'truck.svg' },
  { key: 'tumblr', file: 'tumblr.svg' },
  { key: 'tumblr2', file: 'tumblr2.svg' },
  { key: 'tux', file: 'tux.svg' },
  { key: 'tv', file: 'tv.svg' },
  { key: 'twitch', file: 'twitch.svg' },
  { key: 'twitter', file: 'twitter.svg' },
  { key: 'underline', file: 'underline.svg' },
  { key: 'undo', file: 'undo.svg' },
  { key: 'undo2', file: 'undo2.svg' },
  { key: 'ungroup', file: 'ungroup.svg' },
  { key: 'unlocked', file: 'unlocked.svg' },
  { key: 'upload', file: 'upload.svg' },
  { key: 'upload2', file: 'upload2.svg' },
  { key: 'upload3', file: 'upload3.svg' },
  { key: 'user-check', file: 'user-check.svg' },
  { key: 'user-minus', file: 'user-minus.svg' },
  { key: 'user-plus', file: 'user-plus.svg' },
  { key: 'user-tie', file: 'user-tie.svg' },
  { key: 'user', file: 'user.svg' },
  { key: 'users', file: 'users.svg' },
  { key: 'video-camera', file: 'video-camera.svg' },
  { key: 'vimeo', file: 'vimeo.svg' },
  { key: 'vimeo2', file: 'vimeo2.svg' },
  { key: 'vine', file: 'vine.svg' },
  { key: 'vk', file: 'vk.svg' },
  { key: 'volume-decrease', file: 'volume-decrease.svg' },
  { key: 'volume-high', file: 'volume-high.svg' },
  { key: 'volume-increase', file: 'volume-increase.svg' },
  { key: 'volume-low', file: 'volume-low.svg' },
  { key: 'volume-medium', file: 'volume-medium.svg' },
  { key: 'volume-mute', file: 'volume-mute.svg' },
  { key: 'volume-mute2', file: 'volume-mute2.svg' },
  { key: 'warning', file: 'warning.svg' },
  { key: 'whatsapp', file: 'whatsapp.svg' },
  { key: 'wikipedia', file: 'wikipedia.svg' },
  { key: 'windows', file: 'windows.svg' },
  { key: 'windows8', file: 'windows8.svg' },
  { key: 'wink', file: 'wink.svg' },
  { key: 'wink2', file: 'wink2.svg' },
  { key: 'woman', file: 'woman.svg' },
  { key: 'wondering', file: 'wondering.svg' },
  { key: 'wondering2', file: 'wondering2.svg' },
  { key: 'wordpress', file: 'wordpress.svg' },
  { key: 'wrench', file: 'wrench.svg' },
  { key: 'xing', file: 'xing.svg' },
  { key: 'xing2', file: 'xing2.svg' },
  { key: 'yahoo', file: 'yahoo.svg' },
  { key: 'yahoo2', file: 'yahoo2.svg' },
  { key: 'yelp', file: 'yelp.svg' },
  { key: 'youtube', file: 'youtube.svg' },
  { key: 'youtube2', file: 'youtube2.svg' },
  { key: 'zoom-in', file: 'zoom-in.svg' },
  { key: 'zoom-out', file: 'zoom-out.svg' },
]
